---
pool:
  name: "Azure Pipelines"
  vmImage: "ubuntu-latest"

trigger:
  - master

parameters:
- name: version
  displayName: build versoin
  type: string
  default: v1.0

jobs:
  - job: build_job
    displayName: build students courses rest api
    steps:
      - task: Docker@2
        inputs: 
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: $(build.build.id)
          


