---
pool:
  name: "Azure Pipelines"
  vmImage: "ubuntu-latest"

trigger:
  - master

parameters:
- name: version
  displayName: build versoin
  type: string
  default: v1.0-1
  values:
    - v1.0-2
    - v1.0-3


jobs:
  - job: preparation_job
    displayName: install docker
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
  - job: build_job
    displayName: build students courses rest api
    steps:
      - task: Docker@2
        inputs: 
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: 


