
parameters:
- name: command
  displayName: command
  type: string
  default: 'build'
  values: 
    - 'build'
    - 'buildAndPush'
    - 'push'

steps:
  - task: Docker@2
    inputs: 
      containerRegistry: 'Docker'
      repository: 'srikanthvelma/azuredevops'
      command: "${{ parameters.command }}"
      tags: 'latest'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'images'
      artifact: 'srdocker'