---
  pool:
    name: "Default"
  
  trigger:
    - main
  
  stages:
    - stage: BuildStage
      displayName: Building nop package
      jobs:
        - job: DotnetJob
          displayName: Dotnet
          steps:
            - task: DotNetCoreCLI@2
              inputs:
                command: 'build'
                projects: ~/nopCommerce/src
  
     
    