---
pool:
  name: "Azure Pipelines"
  vmImage: "ubuntu-latest"

trigger:
  - main

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      publishWebProjects: true
      publishTestResults: true 
