---
pool:
  name: "Default"

trigger:
  - main

steps:
  - script: "ansible-playbook -i hosts javamultiver.yml"
    workingDirectory: ./Playbooks/java
    displayName: installing java through playbook