# template for java based projects using maven
parameters:
  - name: mavenPomFile
    displayName: pom file
    type: string
    default: 'pom.xml'
  - name: goal
    displayName: maven goal
    type: string
    default: 'package'
    values: 
      - 'package'
      - 'build'
      - 'clean'
      - 'compile'
  - name: jdkVersion
    displayName: java version
    type: string
    default: '1.11'
  - name: PathtoPublish
    displayName: path to publish
    type: string
    default: 'target/spring-petclinic-2.7.3.jar'
  - name: mavenAuthenticateFeed
    displayName: Authentic to maven feed
    type: boolean
    default: true

    
stages:
  - stage: Devlopment
    displayName: "Dev Environment"
    jobs:
      - job: buildNdpublish
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: "${{ parameters.mavenPomFile }}"
              goals: "${{ parameters.goal }}"
              publishJUnitResults: yes
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: "${{ parameters.jdkVersion }}"  
              mavenAuthenticateFeed: "${{ parameters.mavenAuthenticateFeed }}"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "${{ parameters.PathtoPublish }}" 
              ArtifactName: 'drop' 
              publishLocation: 'Container'  
            
