---
pool:
  name: "Azure Pipelines"
  vmImage: "ubuntu-latest"

trigger:
  - main

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: "pom.xml"
      goals: package
      publishJUnitResults: yes
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      jdkVersionOption: '1.11'
      